### ISSUE TITLE
Periodical errors in Homebridge log

### ISSUE THREAD

**Issue by ovidiu31** [nitaybz/homebridge-sensibo-ac#27]
Hello
At least 1 time per hour this error is thrown into the Hombridge log 

8/12/2020, 11:45:28 PM] [SensiboAC] ERROR getting devices status from API!
[8/12/2020, 11:47:03 PM] [SensiboAC] ERROR Making a Request!! ------->
[8/12/2020, 11:47:03 PM] [SensiboAC] FetchError: request to https://home.sensibo.com/api/v2/users/me/pods?apiKey=**`APIKEYREMOVEDSECURITYPURPOSES`**&fields=id,acState,measurements,location,occupancy,smartMode&integration=homebridge-sensibo-ac@1.1.18 failed, reason: getaddrinfo EAI_AGAIN home.sensibo.com
    at ClientRequest.<anonymous> (/homebridge/node_modules/homebridge-sensibo-ac/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'

**Comment by nitaybz** [comment]
It's the periodic state check, it can be due to no internet connectivity on that moment or issue with Sensibo's servers.

Anyway, it's not an issue if it doesn't bring HomeBridge down and don't prevent you from doing anything with HomeKit

**Comment by ovidiu31** [comment]
@nitaybz 

Yes it was issue with Sensibo's servers .  Since this morning error did not shown in the log anymore.
Thank you very much
