### ISSUE TITLE
Accessory unresponsive and crashing homebridge

### ISSUE THREAD

**Issue by lwndow** [nitaybz/homebridge-sensibo-ac#3]
Hi,

Thanks for the work so far. Saw this new module and installed this morning, but it's crashing Homebridge, here's the error from my logs (temp is obviously wrong, maybe a celsius reading?):

```
homebridge_1  | [5/11/2020, 3:29:19 PM] Homebridge is running on port 51912.
homebridge_1  | [5/11/2020, 3:29:35 PM] [SensiboAC] Getting Devices State
homebridge_1  | [5/11/2020, 3:29:35 PM] [SensiboAC] making a request: https://home.sensibo.com/api/v2/users/me/pods?apiKey=***********&fields=id,acState,measurements&integration=homebridge-sensibo-ac@1.0.3
homebridge_1  | [5/11/2020, 3:29:35 PM] [SensiboAC] Getting AC Swing State Gym AC
homebridge_1  | [5/11/2020, 3:29:35 PM] [SensiboAC] Gym AC Swing - Device is OFF
homebridge_1  | [5/11/2020, 3:29:35 PM] [SensiboAC] Getting AC Rotation Speed Gym AC
homebridge_1  | [5/11/2020, 3:29:35 PM] [SensiboAC] Gym AC AC Rotation Speed - Device is OFF
homebridge_1  | [5/11/2020, 3:29:35 PM] [SensiboAC] Getting Temperature Display Units Gym AC
homebridge_1  | [5/11/2020, 3:29:35 PM] [SensiboAC] The current temperature display unit is ºF
homebridge_1  | [5/11/2020, 3:29:35 PM] [SensiboAC] Getting Cooling Threshold Temperature Gym AC
homebridge_1  | [5/11/2020, 3:29:35 PM] [SensiboAC] Getting Active State Gym AC
homebridge_1  | [5/11/2020, 3:29:35 PM] [SensiboAC] Gym AC Active AC State is 0
homebridge_1  | [5/11/2020, 3:29:35 PM] [SensiboAC] Getting Room Temperature Gym AC
homebridge_1  | [5/11/2020, 3:29:35 PM] [SensiboAC] Gym AC Current Temperature is 22.2ºF
homebridge_1  | [5/11/2020, 3:29:35 PM] TypeError: Assignment to constant variable.
homebridge_1  |     at acAccessory.getCurrentTemperature (/homebridge/node_modules/homebridge-sensibo-ac/lib/accessories.js:317:9)
homebridge_1  |     at CurrentTemperature.emit (events.js:310:20)
homebridge_1  |     at CurrentTemperature.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
homebridge_1  |     at CurrentTemperature.Characteristic._this.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:451:12)
homebridge_1  |     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1219:22
homebridge_1  |     at Array.forEach (<anonymous>)
homebridge_1  |     at Bridge.Accessory._this._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1147:10)
homebridge_1  |     at HAPServer.emit (events.js:310:20)
homebridge_1  |     at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
homebridge_1  |     at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:900:12)
homebridge_1  | [5/11/2020, 3:29:35 PM] Got SIGTERM, shutting down Homebridge...
homebridge_1  | [5/11/2020, 3:29:36 PM] [SensiboAC] GET Response:
homebridge_1  |  {"status":"success","result":[{"acState":{"on":false,"nativeTargetTemperature":25,"fanLevel":"quiet","temperatureUnit":"F","targetTemperature":77,"nativeTemperatureUnit":"C","mode":"cool","swing":"fixedTop"},"measurements":{"batteryVoltage":null,"temperature":22.2,"humidity":58.3,"time":{"secondsAgo":7,"time":"2020-05-11T15:29:28.107246Z"},"rssi":-50,"piezo":[null,null]},"id":"********"}]}
homebridge_1  | [5/11/2020, 3:29:36 PM] [SensiboAC] Finished updating state in HomeKit for ix8PN9Fv:
homebridge_1  | [5/11/2020, 3:29:36 PM] [SensiboAC] null
homebridge_1  | [5/11/2020, 3:29:36 PM] [SensiboAC] null
homebridge_1  | [5/11/2020, 3:29:40 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
homebridge_1  | [5/11/2020, 3:29:45 PM] [HB Supervisor] Restarting Homebridge...
homebridge_1  | [5/11/2020, 3:29:45 PM] [HB Supervisor] Starting Homebridge with extra flags: -P /homebridge/node_modules
homebridge_1  | [5/11/2020, 3:29:46 PM] [HB Supervisor] Started Homebridge v1.0.4 with PID: 1108
homebridge_1  | [5/11/2020, 3:29:46 PM] Loaded config.json with 0 accessories and 1 platforms.
```

Please let me know if there's anything else I can provide/fetch. Running Homebridge on a raspberry pi in a docker container.

**Comment by nitaybz** [comment]
Please reinstall the plugin, the issue should be solved...
One thing I should mention is that I haven't tested the plugin in Fahrenheit yet... let me know if it all acts well.

**Comment by lwndow** [comment]
Good deal, no longer crashing. Will open a new issue for rendering Fahrenheit. Something else might be odd there too, need to investigate.
