### ISSUE TITLE
Error: This callback function has already been called by someone else; it can only be called one time.

### ISSUE THREAD

**Issue by raeldor** [nitaybz/homebridge-sensibo-ac#46]
Hi,

I am seeing the following errors in my log and it seems a bit hit-and-miss when I go into home as to whether the devices respond quickly enough.  It seems that HomeBridge is crashing and restarting.  Plug-ins are up to date and this is the only plug-in I'm running.  Thanks.

Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 266-42-217 │     
    └────────────┘     
                       
[1/19/2021, 06:33:13] Homebridge is running on port 51594.
(node:1131) UnhandledPromiseRejectionWarning: Error: Cannot add a Service with the same UUID '00000049-0000-1000-8000-0026BB765291' and subtype 'SyncButton' as another Service in this Accessory.
    at Accessory._this.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:281:17)
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:92:41)
    at AirConditioner.addSyncButtonService (/usr/local/lib/node_modules/homebridge-sensibo-ac/homekit/AirConditioner.js:324:44)
    at new AirConditioner (/usr/local/lib/node_modules/homebridge-sensibo-ac/homekit/AirConditioner.js:96:9)
    at /usr/local/lib/node_modules/homebridge-sensibo-ac/sensibo/syncHomeKitCache.js:18:28
    at Array.forEach (<anonymous>)
    at SensiboACPlatform.syncHomeKitCache (/usr/local/lib/node_modules/homebridge-sensibo-ac/sensibo/syncHomeKitCache.js:10:20)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-sensibo-ac/index.js:102:9)
(node:1131) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1131) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1131) UnhandledPromiseRejectionWarning: Error: Cannot add a Service with the same UUID '00000049-0000-1000-8000-0026BB765291' and subtype 'SyncButton' as another Service in this Accessory.
    at Accessory._this.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:281:17)
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:92:41)
    at AirConditioner.addSyncButtonService (/usr/local/lib/node_modules/homebridge-sensibo-ac/homekit/AirConditioner.js:324:44)
    at new AirConditioner (/usr/local/lib/node_modules/homebridge-sensibo-ac/homekit/AirConditioner.js:96:9)
    at /usr/local/lib/node_modules/homebridge-sensibo-ac/sensibo/syncHomeKitCache.js:18:28
    at Array.forEach (<anonymous>)
    at SensiboACPlatform.syncHomeKitCache (/usr/local/lib/node_modules/homebridge-sensibo-ac/sensibo/syncHomeKitCache.js:10:20)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-sensibo-ac/sensibo/refreshState.js:68:14)
(node:1131) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[1/19/2021, 12:11:08] Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at Characteristic.FanActive (/usr/local/lib/node_modules/homebridge-sensibo-ac/homekit/StateManager.js:155:6)
    at Characteristic.emit (events.js:322:22)
    at Characteristic.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Characteristic._this.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:489:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1217:22
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1145:10)
    at HAPServer.emit (events.js:310:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
[1/19/2021, 12:11:08] Got SIGTERM, shutting down Homebridge...
[1/19/2021, 12:11:13] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[1/19/2021, 12:11:18] [HB Supervisor] Restarting Homebridge...

**Comment by nitaybz** [comment]
Please add debug logs to your config  and share your config and logs afterwards. Don't forget to deleted or hide private information

**Comment by raeldor** [comment]
Hi,

My config is...

{
    "bridge": {
        "name": "Homebridge F2BA",
        "username": "0E:7D:61:E3:F2:BA",
        "port": 51594,
        "pin": "266-42-217"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "username": "xxx@xxx.com",
            "password": "xxx",
            "disableFan": false,
            "disableDry": false,
            "enableSyncButton": true,
            "syncButtonInAccessory": true,
            "enableOccupancySensor": false,
            "enableClimateReactSwitch": false,
            "enableHistoryStorage": false,
            "disableHorizontalSwing": false,
            "externalHumiditySensor": false,
            "debug": true,
            "platform": "SensiboAC"
        }
    ]
}

The output from the log after enabling debug is now as follows...

[1/18/2021, 21:44:56] Homebridge is running on port 51594.
(node:656) UnhandledPromiseRejectionWarning: Error: Cannot add a Service with the same UUID '00000049-0000-1000-8000-0026BB765291' and subtype 'SyncButton' as another Service in this Accessory.
    at Accessory._this.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:281:17)
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:92:41)
    at AirConditioner.addSyncButtonService (/usr/local/lib/node_modules/homebridge-sensibo-ac/homekit/AirConditioner.js:324:44)
    at new AirConditioner (/usr/local/lib/node_modules/homebridge-sensibo-ac/homekit/AirConditioner.js:96:9)
    at /usr/local/lib/node_modules/homebridge-sensibo-ac/sensibo/syncHomeKitCache.js:18:28
    at Array.forEach (<anonymous>)
    at SensiboACPlatform.syncHomeKitCache (/usr/local/lib/node_modules/homebridge-sensibo-ac/sensibo/syncHomeKitCache.js:10:20)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-sensibo-ac/index.js:102:9)
(node:656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:656) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1/18/2021, 21:44:59] [Homebridge UI] Homebridge Config UI X v4.36.0 is listening on :: port 8581
[1/18/2021, 23:39:14] [SensiboAC] Living Room AC  -> Setting New State:
[1/18/2021, 23:39:14] [SensiboAC] {
  "on": false,
  "mode": "heat",
  "temperatureUnit": "C",
  "targetTemperature": 21,
  "swing": "stopped",
  "fanLevel": "auto"
}
(node:656) UnhandledPromiseRejectionWarning: Error: Cannot add a Service with the same UUID '00000049-0000-1000-8000-0026BB765291' and subtype 'SyncButton' as another Service in this Accessory.
    at Accessory._this.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:281:17)
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:92:41)
    at AirConditioner.addSyncButtonService (/usr/local/lib/node_modules/homebridge-sensibo-ac/homekit/AirConditioner.js:324:44)
    at new AirConditioner (/usr/local/lib/node_modules/homebridge-sensibo-ac/homekit/AirConditioner.js:96:9)
    at /usr/local/lib/node_modules/homebridge-sensibo-ac/sensibo/syncHomeKitCache.js:18:28
    at Array.forEach (<anonymous>)
    at SensiboACPlatform.syncHomeKitCache (/usr/local/lib/node_modules/homebridge-sensibo-ac/sensibo/syncHomeKitCache.js:10:20)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-sensibo-ac/sensibo/refreshState.js:68:14)
(node:656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[1/19/2021, 01:42:51] [Homebridge UI] Running job to cleanup config.json backup files older than 60 days...
[1/19/2021, 01:42:51] [Homebridge UI] Running scheduled instance backup...
[1/19/2021, 01:42:51] [Homebridge UI] Creating temporary backup archive at /tmp/homebridge-backup-YKBE6X/homebridge-backup-0E7D61E3F2BA.tar.gz
[1/19/2021, 06:33:00] Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at Characteristic.FanSwing (/usr/local/lib/node_modules/homebridge-sensibo-ac/homekit/StateManager.js:169:5)
    at Characteristic.emit (events.js:322:22)
    at Characteristic.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Characteristic._this.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:489:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1217:22
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1145:10)
    at HAPServer.emit (events.js:310:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
[1/19/2021, 06:33:00] Got SIGTERM, shutting down Homebridge...
[1/19/2021, 06:33:05] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[1/19/2021, 06:33:10] [HB Supervisor] Restarting Homebridge...

Thanks

**Comment by raeldor** [comment]
I just discovered that if I turn off the 'Sync Button in AC Accessory' the error goes away.  Is this and the 'Enable Sync' button mutually exclusive?

**Comment by nitaybz** [comment]
that shouldn't happen and will be fixed... what happened is it created 2 accessories with the same ID. it's completely code error, I should make sure only 1 accessory stays.

**Comment by nitaybz** [comment]
please test it again... it shouldn't happen now on version 2.0.23

**Comment by raeldor** [comment]
Hi, I upgraded to the new version and re-enabled the sync buttons.  So far, no errors.  Thank you for fixing! On another note, I was able to rename the accessory in the Home app as you suggested, but still kind of confused why it’s showing the old name in Homebridge.  Where are these names coming from?...  Ray Sent from Mail for Windows 10 From: Nitay Ben-ZviSent: Wednesday, January 27, 2021 5:11 PMTo: nitaybz/homebridge-sensibo-acCc: Ray Price; AuthorSubject: Re: [nitaybz/homebridge-sensibo-ac] Error: This callback function has already been called by someone else; it can only be called one time. (#46) please test it again... it shouldn't happen now on version 2.0.23—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by nitaybz** [comment]
not sure changing HomeKit names should affect Homebridge names... as far as I know it goes only one way.
anyway, this it not related to the issue anymore so I'm closing...
