### ISSUE TITLE
Homebridge-Sensibo stopped working

### ISSUE THREAD

**Issue by MF-Bra** [nitaybz/homebridge-sensibo-ac#65]
It just stopped working here.
Tried to restart whole homebridge services but nothing changed… the message i get just after issue a command using Home.app is this.                                                             

[7/16/2021, 10:23:44 PM] [homebridge-sensibo-ac] This plugin threw an error from the characteristic 'Active': Unhandled error thrown inside read handler for characteristic: This callback function has already been called by someone else; it can only be called one time.. See https://git.io/JtMGR for more info.
[7/16/2021, 10:23:44 PM] [homebridge-sensibo-ac] Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:6:13
    at Characteristic.ACActive (/usr/lib/node_modules/homebridge-sensibo-ac/homekit/StateManager.js:50:6)
    at Characteristic.emit (events.js:327:22)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at Characteristic.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>).                                                          

 Any ideas. ?

I’m Running Homebridge v1.3.4 / Sensibo-ac 2.2.0 / Homebridge-ISY 0.5Rc23.   ISY devices still working.

**Comment by benwebbbenwebb** [comment]
Hi @MF-Bra 

Are you still seeing this issue?

As there's been a few code changes since you reported this do please confirm that you're on the latest version and provide the updated error message(s) / stacktrace. Otherwise I'll probably close this off in a week or so.

Thanks

**Comment by MF-Bra** [comment]
Sorry. Everything is fine. After update it fixed. I'm struggling with sensibo node server for polyglot.... Digging it right now. thanks.

**Comment by benwebbbenwebb** [comment]
No worries, thanks for the confirmation @MF-Bra
