### ISSUE TITLE
Sensibo plugin stopping HOOBS bridge

### ISSUE THREAD

**Issue by dominvepf** [nitaybz/homebridge-sensibo-ac#7]
Hi all, I am very new to this and this is the first day that I actually turned on the AC, we still had snowfall here 17 days ago but toady is super hot.

At first I didn't think sensible was the problem I assumed I needed to update to latest Hobby, but it still kept on failing so I also upgraded to latest sensible, but it still kept on failing so I went to the log and found this error when the bridge was stopped: 
2020-05-27 21:47:27 TypeError: Cannot read property 'filter' of undefined
    at fanLeveltoHK (/home/hoobs/.hoobs/node_modules/homebridge-sensibo-ac/lib/accessories.js:969:24)
    at acAccessory.getDryRotationSpeed (/home/hoobs/.hoobs/node_modules/homebridge-sensibo-ac/lib/accessories.js:604:19)
    at RotationSpeed.emit (events.js:310:20)
    at RotationSpeed.EventEmitter.emit (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/EventEmitter.js:59:38)
    at RotationSpeed.Characteristic._this.getValue (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Characteristic.js:190:23)
    at /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:753:32
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/Accessory.js:694:18)
    at HAPServer.emit (events.js:310:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/EventEmitter.js:59:38)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:664:23)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/HAPServer.js:227:39)
    at IncomingMessage.emit (events.js:310:20)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-05-27 21:47:27 Got SIGTERM, shutting down Bridge...
[sensibo log.txt](https://github.com/nitaybz/homebridge-sensibo-ac/files/4692784/sensibo.log.txt)

I guess I have to uninstall for now so as to keep the other plugins and the bridge working, but I'd love to see the AC in home kit and be able to use it again. It seems the issue only started since I have been using the AC for real.

Thanks for any help, much obliged

Dominic

**Comment by nitaybz** [comment]
Hey man!
Thanks for your feedback, Please install the latest @1.0.8 and let me know please

**Comment by nitaybz** [comment]
fixed

**Comment by dominvepf** [comment]
Hi Sorry I was never able to upgrade to the new version to try the fix, I have opened a new issue (#23) about that problem and include more details there.

Thanks,
_________________________________________________________________
Dominic Villeneuve, Ph. D.
dominicvilleneuve@live.ca <mailto://dominicvilleneuve@live.ca> | Web: http://DominicVilleneuve.ca <http://dominicvilleneuve.ca/>
